ci: check for code 5 (no tests)

diff --git a/.github/workflows/python-test-tutorial-and-to-readme.yml b/.github/workflows/python-test-tutorial-and-to-readme.yml
--- a/.github/workflows/python-test-tutorial-and-to-readme.yml
+++ b/.github/workflows/python-test-tutorial-and-to-readme.yml
@@ -35,3 +35,11 @@ jobs:
       - name: Test with pytest
         run: |
           pytest dyada_tutorial.py
+          test_error_code=$?
+          if [ "$test_error_code" -ne 5 ]; then
+            # no tests ran
+            echo "wrong pytest return code $test_error_code"
+          else
+            echo "pytest returned expected code 5"
+            exit 0
+          fi
